shoefony_store:
    resource: "@ShoefonyStoreBundle/Controller/"
    type:     annotation
    prefix:   /store

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

shoefony_cms:
    resource: "@ShoefonyCmsBundle/Controller/"
    type:     annotation
    prefix:   /

shoefony_admin:
    resource: "@ShoefonyAdminBundle/Controller"
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile